apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  labels:
    type: mysql
    name: jegan
spec:
  selector:
    matchLabels:
      type: mysql
      name: jegan
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
